app_env="development"
server_address="localhost"
port="3306"
user="root"
password="20050613"
dbname="gin_jwt_gorm"
ACCESS_TOKEN_EXPIRY_HOUR=""
REFRESH_TOKEN_EXPIRY_HOUR=""
ACCESS_TOKEN_SECRET=""
REFRESH_TOKEN_SECRET=""